# This file defines the Kubernetes deployment and service for Kibana, which is a data visualization tool that works with Elasticsearch. The deployment specifies the number of replicas, the container image to use, and the environment variables needed to connect to Elasticsearch. The service exposes Kibana on a specific port so that it can be accessed from outside the cluster.
# Kibana will be deployed as a single instance for simplicity, but it can be scaled to multiple instances for production use. The deployment includes a Service to expose the Kibana UI.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
spec:
  replicas: 1 #only 1 instance of kibana is needed to visualize the logs, but it can be scaled to multiple instances for high availability in production use
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.17.0
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
          ports:
            - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - port: 5601
      nodePort: 30601